language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - 'node_modules'
script:
  - npm run test:coverage
  - npm run build
after_script:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage