language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - 'node_modules'
    - 'api/node_modules'
before_Script:
  - npm install && cd api && npm install && cd ../
script:
  - npm run test:coverage
  - npm run build
after_script:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage