language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - 'node_modules'
    - 'api/node_modules'
before_install:
  - cd ./api
  - npm install
  - cd ./
  - npm install
script:
  - npm run test
after_success:
  - npm run test:coverage
  - npm run build
after_script:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage