language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - 'node_modules'
    - '${TRAVIS_BUILD_DIR}/api/node_modules'
before_install:
  - cd ${TRAVIS_BUILD_DIR}/api
  - npm install
  - cd ${TRAVIS_BUILD_DIR}
  - npm install
script:
  - node bin/prepare-data ebe991d6e14ff4827c66160ead08031f999df8aa
  - npm run test
after_success:
  - npm run test:coverage
  - npm run build
after_script:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage